# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to Firebase"
  lane :beta do
    increment_build_number(xcodeproj: "MSA.xcodeproj")
    build_app(workspace: "MSA.xcworkspace", scheme: "MSA", export_method: "ad-hoc", silent: "false", output_directory: "./build_ipa")
firebase_app_distribution(
 app: “1:317876705372:ios:e7db0c5bccc4125ea66e99”,
 groups: “testers”,
 release_notes: “Lots of amazing new features to test out!”,
 firebase_cli_path: “/usr/local/bin/firebase” )
  end
end
